### ISSUE TITLE
震度データベース上の一部の地震が閲覧できない。

### ISSUE THREAD

**Issue by CaffeeLake** [EQMonitor/EQMonitor#777]
## 再現方法

- 震度データベースから以下の地震を閲覧しようとする。

## 再現する地震

- 1958/11/07 07:58:12 択捉島南東沖 深さ13km M8.1
- 1955/05/30 21:33 硫黄島近海 深さ600km M7.5
- 1953/11/26 02:48:58 関東東方沖 深さ39km M7.4
- 1951/07/12 03:21:58 小笠原諸島西方沖 深さ490km M7.2

## 再現環境

- Google Play版 EQMonitor 2.6.0
- Android 14 & Android 13

## エラー画面

![Screenshot_20240814-175834_EQMonitor~2](https://github.com/user-attachments/assets/d8e5018d-3664-4d6d-ab76-b694e69d202b)

**Comment by CaffeeLake** [comment]
すいません。
2.6.1で既に修正されていました。
https://github.com/YumNumm/EQMonitor/pull/768/

**Comment by YumNumm** [comment]
@CaffeeLake Issue作成ありがとうございます🙏
数日中にBigFixの2.6.1をリリースする予定ですので もうしばらくお待ちいただけますようお願いいたします🙏
